// TodoList.React/ClientApp/components/Contact.tsx
import * as React from 'react';
import { RouteComponentProps } from 'react-router';


export class Contact extends React.Component<RouteComponentProps<{}>, {}> {
    public render() {
        return <div>
            <h1>Contact</h1>
            <address>
                One Microsoft Way<br />
                Redmond, WA 98052-6399<br />
                <abbr title="Phone">P:</abbr>
                425.555.0100
            </address>

            <address>
                <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
                <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
            </address>
        </div>;
    }
}

// TodoList.Angular/ClientApp/app/components/contact/contact.component.ts
﻿import { Component } from '@angular/core';

@Component({
    templateUrl: './contact.component.html'
})
export class ContactComponent {
    pageTitle: string = 'Contact';
    message: string = 'Your contact page.';
}
﻿<h2>{{pageTitle}}</h2>
<h3>{{message}}</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>
